import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { Container } from "@/components/common/container";
import localFont from "next/font/local";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

const thunder = localFont({
  src: "./../../public/fonts/Thunder-LC.ttf",
  display: "swap",
  variable: "--font-thunder",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${onest.variable} ${thunder.variable}  antialiased`}
        cz-shortcut-listen="true"
      >
        <Container>{children}</Container>
      </body>
    </html>
  );
}

